version: '3'
services:

  node:
    build: '.'
    volumes:
      - '.:/node'
    ports:
      - 3000:3000
    command: npm start
    environment: 
      - NODE_ENV=development
      - PORT=3000
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
